events {}

http {
    upstream my_backend_app {
        server backend:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://my_backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}