events {}

http {
    # Define the group of servers to distribute traffic to
    upstream my_backend_app {
        # 'backend' matches the service name in docker-compose.yml
        server backend:3000;
    }

    server {
        listen 80;

        location / {
            # Forward traffic to the upstream group
            proxy_pass http://my_backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}