services:
  backend:
    build: ./backend
    deploy:
      replicas: 2
    networks:
      - day3_net

  nginx:
    image: nginx:latest
    container_name: load-balancer
    ports:
      - "8080:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - day3_net

networks:
  day3_net:
    driver: bridge