events {}

http {
    upstream backend_api {
        server backend:3000;
    }

    upstream frontend_ui {
        server frontend:80;
    }

    server {
        listen 80;
        server_name sneaker-hub.local localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name sneaker-hub.local localhost;

        ssl_certificate /etc/nginx/certs/day5.pem;
        ssl_certificate_key /etc/nginx/certs/day5-key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location /api/ {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://frontend_ui;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme; 
        }
    }
}